### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by hheekwak** [hhsw0322/CS596-RT2024Fall-Group01#2]
Hello Group 01, 

While I was grading, your source code faced several compile errors. I screen captured and attached part of them. Grading will be on hold until the issues are fixed. Let me know when the fixed is ready. 

Hope it helps, 

Hyunhee

![group1_compile_error_1](https://github.com/user-attachments/assets/2b96be4b-e981-45a8-88e5-aef2e8121d0a)
![group1_compile_error_2](https://github.com/user-attachments/assets/12f8ec4b-59c7-46ce-8d91-9c31973363f1)
![group1_lkm_compile_error](https://github.com/user-attachments/assets/43f2a0f9-01c9-4d9a-a21a-2cedc5d28fc3)

**Comment by hhsw0322** [comment]
Hi,

Noted!
We’ll let you know soon since we will be meeting up tomorrow so we should
have it fixed by end of tomorrow.

Best,
Su
